name: build-go-binary

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude: 
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@4.2.2
      - uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.24.2 
          binary_name: "mam" 
          extra_files: README.md LICENSE 
          compress_assets: auto
